//LOGIN ACTION TYPES
export const LOGIN_REQUEST_PENDING = "LOGIN_REQUEST_PENDING";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

//SIGNUP ACTION TYPES
export const SIGNUP_REQUEST_PENDING = "SIGNUP_REQUEST_PENDING";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAILURE = "SIGNUP_REQUEST_FAILURE";

//USER PROFILE ACTION TYPES
export const USER_PROFILE_REQUEST_SUCCESS = "USER_PROFILE_REQUEST_SUCCESS";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

//USER CV ACTION TYPES
export const UPDATE_USER_CV_SUCCESS = "UPDATE_USER_CV_SUCCESS";
export const UPDATE_USER_CV_FAILURE = "UPDATE_USER_CV_FAILURE";

//APPLICATIONS ACTION TYPES
export const APPLICATIONS_DATA_SUCCESS = "APPLICATIONS_DATA_SUCCESS";
export const APPLICATIONS_DATA_PENDING = "APPLICATIONS_DATA_PENDING";

export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
export const CLEAR_USER_MESSAGE = "CLEAR_USER_MESSAGE";
